### ISSUE TITLE
Don't emit events to the document

### ISSUE THREAD

**Issue by hydrabolt** [TeamCernodile/JSCord#1]
There is no logic behind emitting events to the document if the events are linked to a specific client. If you had more than one client this would get confusing.

**Comment by cernodile** [comment]
Hm, I've tried to do something like bot.on(), but I couldn't get my head around it, maybe I should add option to choose the node it listens from?

**Comment by hydrabolt** [comment]
https://github.com/Olical/EventEmitter/blob/master/README.md

**Comment by cernodile** [comment]
Alright, I'll give it a read. Thanks for linking it.
Will be addressed next update.
