### ISSUE TITLE
Ratelimits

### ISSUE THREAD

**Issue by cernodile** [TeamCernodile/JSCord#2]
Okay, so, I've stumbled upon a very big issue.. I can't get the ratelimit headers because of CORS. It could be fixed in PHP, but HTML users would have issues with it. Any help would be appreciated.

**Comment by hydrabolt** [comment]
there is no way around this without PHP unless you stopped once hitting a 429

**Comment by cernodile** [comment]
So, what should I do? Any idea?

**Comment by hydrabolt** [comment]
You won't be able to become compliant with rate limiting without PHP, the
only solution is to keep making requests until a 429 but it still won't
make JSCord compliant

**Comment by cernodile** [comment]
So, I should make it both ways, check if can CORS, if can't, then do once hit 429?

**Comment by cernodile** [comment]
TODO: PHP CORS

**Comment by cernodile** [comment]
Status update:
PHP CORS Proxy is currently being worked at. Will be released somewhere around next week. With upcoming change, the ratelimits are properly handled.

**Comment by cernodile** [comment]
UPDATE:
Since one of the Discord devs made CORS headers for x-ratelimit headers, there is a EXPERIMENTAL ratelimit thingie at the dev branch!
Keep in mind it still needs YOU to have exact time, and depends on system a lot, I'll be changing it to look from a trusted server soon!

**Comment by cernodile** [comment]
So this should be usable for now, I'm still looking around for more solutions.. will update when found!
